# render.yaml

services:
  # =====================
  # Backend Service
  # =====================
  - type: web
    name: todo-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: MODEL
        sync: false 
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DEVELOPMENT
        value: "false"
      - key: BACKEND_PORT
        value: "7001"
    autoDeploy: true

  # =====================
  # Frontend Service
  # =====================
  - type: web
    name: todo-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          name: todo-backend
          type: web
          property: host
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        sync: false
      - key: FRONTEND_PORT
        value: "3000"
    autoDeploy: true
